# Generated by Django 4.2.13 on 2024-06-13 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65, verbose_name='')),
                ('description', models.CharField(max_length=165, verbose_name='')),
                ('slug', models.SlugField(verbose_name='')),
                ('preparation_time', models.IntegerField(verbose_name='')),
                ('preparation_time_unit', models.CharField(max_length=65, verbose_name='')),
                ('servings', models.IntegerField(verbose_name='')),
                ('servings_unit', models.CharField(max_length=65, verbose_name='')),
                ('preparation_steps', models.TextField(verbose_name='')),
                ('preparation_steps_is_html', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='')),
                ('is_published', models.BooleanField(default=False)),
                ('cover', models.ImageField(upload_to='recipe/covers/%Y/%m/%d/', verbose_name='')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='recipe.category')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='recipe.category')),
            ],
        ),
    ]
